# Generated by Django 3.2.9 on 2021-12-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='availableQuantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
