# Generated by Django 3.2.9 on 2021-12-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_store', '0003_alter_order_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerId',
            field=models.CharField(default='xyz', max_length=200),
        ),
    ]
