# Generated by Django 3.2.9 on 2021-12-07 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retail_store', '0004_alter_order_customerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='productId',
            new_name='productName',
        ),
        migrations.AlterField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
